# DRY - Don't Repeat Yourself

print('Hello, World!')
print('Hello, World!')
print('Hello, World!')
print('Hello, world!')
print('Hello, world!')
print('Hello, world!')
print('Hello, world!')
print('Hello, world!')
print('Hello, world!')
print('Hello, world!')
print('Hello, world!')
print('Hello, world!')
print('Hello, world!')
print('Hello, world!')
print('Hello, world!')
