services:
  web:
      container_name: web
      build: ./app
      command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
      volumes:
          - ./logs:/logs
      ports:
          - "8000:8000"
      networks:
          - network

  nginx:
      container_name: nginx
      image: nginx:latest
      volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./static:/usr/share/nginx/html
          - ./logs:/var/log/nginx
      ports:
          - "80:80"
      depends_on:
          - web
      networks:
          - network

networks:
  network:
