services:
  web:
    container_name: web
    build: .
    ports:
      - "80:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    volumes:
      - data:/code/data
  redis:  
    container_name: redis
    image: "redis:alpine"

volumes:
  data:

